version: '3.8'

services:
  db:
    image: postgres:15
    container_name: analysis_cost_db
    restart: always
    environment:
      POSTGRES_DB: analysis_cost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"  # 5433 на хосте, чтобы не конфликтовать с локальным 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Сохраняет данные базы в Docker

  app:
    build: .
    container_name: analysis_cost_app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/analysis_cost
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234

volumes:
  postgres_data: